routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/user', function (){
    \Illuminate\Support\Facades\Auth::loginUsingId(2);
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function (){
    return redirect()->route('admin.home');
});

Route::get('/app', function () {
    return view('layouts.spa');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Auth::routes();

    Route::group(['middleware' => 'can:access-admin'], function (){
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('banks', 'Admin\BanksController',['except' => 'show']);
    });
});

app/Models/Bank.php
<?php

namespace CodeFin\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Bank extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'name',
        'logo'
    ];

    public static function logosDir(){
        return 'banks/images';
    }

}

app/Http/Controllers/Api/BanksController.php
<?php

namespace CodeFin\Http\Controllers\Api;

use CodeFin\Http\Controllers\Controller;
use CodeFin\Repositories\BankRepository;

class BanksController extends Controller
{
    /**
     * @var BankRepository
     */
    private $repository;

    /**
     * BanksController constructor.
     * @param BankRepository $repository
     */
    public function __construct(BankRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        return $this->repository->all();
    }
}

app/Http/Controllers/admin/BanksController.php
<?php

namespace CodeFin\Http\Controllers\admin;

use CodeFin\Events\BankCreatedEvent;
use CodeFin\Http\Controllers\Controller;
use CodeFin\Http\Controllers\Response;

use CodeFin\Models\Bank;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use CodeFin\Http\Requests\BankCreateRequest;
use CodeFin\Http\Requests\BankUpdateRequest;
use CodeFin\Repositories\BankRepository;



class BanksController extends Controller
{

    /**
     * @var BankRepository
     */
    protected $repository;


    public function __construct(BankRepository $repository)
    {
        $this->repository = $repository;
        $this->repository->skipPresenter(true);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banks = $this->repository->paginate(5);
        $bank = new Bank();
        $bank->name = "ITAU MLK";
        event(new BankCreatedEvent($bank));
        return view('admin.banks.index', compact('banks'));
    }

    public function create()
    {
        return view('admin.banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  BankCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(BankCreateRequest $request)
    {
        $data = $request->all();
        $this->repository->create($data);
        return redirect()->route('admin.banks.index');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $bank = $this->repository->find($id);

        return view('admin.banks.edit', compact('bank'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  BankUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     */
    public function update(BankUpdateRequest $request, $id)
    {
        $this->repository->update($request->all(), $id);
        return redirect()->route('admin.banks.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Bank deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Bank deleted.');
    }
}

resources/views/admin/banks/_form.blade.php
@include('errors._error_field')
<?php $errorClass = $errors->first('name')? ['class' =>  'validate invalid']:[] ?>
<div class="row">
    <div class="input-field col s6">
        {!! Form::text('name', null, $errorClass) !!}
        {!! Form::label('name', 'Nome', ['data-error' => $errors->first('name')]) !!}
    </div>
    <div class="input-field file-field col s6">
        <div class="btn">
            <span>Logo</span>
            {!! Form::file('logo') !!}
        </div>
        <div class="file-path-wrapper">
            <input type="text" class="file-path"/>
        </div>

    </div>
</div>

resources/views/admin/banks/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <h5>Minhas contas</h5>
            {!! Form::open(['route' => 'admin.banks.store', 'files' => true]) !!}
            @include('admin.banks._form')
            <div class="row">
                {!! Form::submit('Criar banco', ['class' => 'btn waves-effect']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/banks/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <h5>Minhas contas</h5>
            {!! Form::model($bank, [
                    'route' => ['admin.banks.update', 'bank' => $bank->id],
                    'method' => 'PUT',
                    'files' => true
             ]) !!}
            @include('admin.banks._form')
            <div class="row">
                {!! Form::submit('Salvar banco', ['class' => 'btn waves-effect']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/banks/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h2>Minhas contas</h2>
        <a href="{{route('admin.banks.create')}}" class="btn waves-effect">Novo Banco</a>
        <table class="bordered striped highlight centered responsive-table z-depth-5">
            <thead>
            <tr>
                <th>#</th>
                <th class="left">Nome</th>
                <th>Acoes</th>
            </tr>
            </thead>
            <tbody>

            @foreach($banks as $bank)
                <tr>
                    <td>
                        <div class="row valign-wrapper">
                            <div class="col s12">{{ $bank->id }}</div>
                        </div>
                    </td>
                    <td>
                        <div class="row valign-wrapper">
                            <div class="col s2">
                                <img src="{{asset("storage/banks/images/{$bank->logo}")}}" class="bank-logo"/>
                            </div>
                            <div class="col s10">
                                <span class="left">{{ $bank->name }}</span>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="row valign-wrapper">
                            <div class="col s12">
                                <a href="{{route('admin.banks.edit', ['bank' => $bank->id])}}"><i class="material-icons">edit</i></a>
                                <delete-action action="{{route('admin.banks.destroy', ['bank' => $bank->id])}}"
                                               action-element="link-delete-{{$bank->id}}" csrf-token="{{csrf_token()}}">
                                    <?php $modalId = "modal-delete-$bank->id"; ?>
                                    <a id="link-modal-{{$bank->id}}"
                                       href="#{{$modalId}}"><i class="material-icons">delete</i></a>
                                    <modal :modal="{{json_encode(['id' => $modalId])}}" style="display: none">
                                        <div slot="content">
                                            <h4>Mensagem de confirmação</h4>
                                            <p><strong>Deseja excluir este banco?</strong></p>
                                            <div class="divider"></div>
                                            <p>Nome: <strong>{{$bank->name}}</strong></p>
                                            <div class="divider"></div>
                                        </div>
                                        <div slot="footer">
                                            <button class="btn btn-flat waves-effect green lighten-2 modal-close modal-action"
                                                    id="link-delete-{{$bank->id}}">OK</button>
                                            <button class="btn btn-flat waves-effect waves-red modal-close modal-action">Cancelar</button>
                                        </div>
                                    </modal>
                                </delete-action>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $banks->links() !!}
    </div>
</div>
@endsection